### ISSUE TITLE
add code to make a simple map of the wlmax raster

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/ADRAS#2]
Add a small amt of code to make a map figure, using the QGIS python already being used elsewhere. Alternatively, cartopy-based…
Something along these lines (except with the correct graticule labels)

<img width="487" alt="Screen Shot 2021-08-24 at 11 04 41 AM" src="https://user-images.githubusercontent.com/2234435/130641276-ba073b91-96ff-4d90-bce4-6bdba6ac9caf.png">

**Comment by jmpmcmanus** [comment]
@BrianOBlanton I looked at the ADRAS repo, and there is no longer a HAZUS branch. Should I be using the master branch?

**Comment by jmpmcmanus** [comment]
@BrianOBlanton One thing that is unclear to me in your discussion above is if you want me to use the qgis that is the adcirc2mbtiles container, or create a new one that I create in a branch of ADRAS? It will probably be more strait forward to use the existing one in the adcirc2mbtiles container.  From what I understand you are already producing output of the ADRAS/HAZUS code in ApsViz. I could develop a python script in adcirc2mbtiles that would pick up the appropriate output from ADRAS/HAZUS and make the map figure. Does that make sense to you, or am I misunderstanding what you want?

**Comment by BrianOBlanton** [comment]
@jmpmcmanus  Yes, branch the "main" repo.  "hazus" was merged into main. 
 
Strictly speaking, the ADRAS image computes geotiffs that get uploaded to AWS s3://hazus.  these images do not get ingested by geoserver for APSviz display, although this is managed by the supervisor. 

I don't think that having adcirc2mbtiles should make this map, bec I think the images need to do as little work as possible, and in this case it would generate a dependency between images that could be hard to break in the long-run. 

Let's consider adding  a small function that would (optionally) make a simple map as a final step in ADRAS.

I mentioned QGIS/python, but that is probably overkill for this.  Perhaps just a few lines of code that uses Cartopy would be easier and lighter-weight. 
 
I'll dig up a short cartopy example shortly.

**Comment by jmpmcmanus** [comment]
Done.
